// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Web.Api.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20200528195910_InitialData")]
    partial class InitialData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "Post body 1",
                            CreatedOn = new DateTime(2020, 5, 28, 21, 59, 10, 482, DateTimeKind.Local).AddTicks(6919),
                            Title = "Post Title 1"
                        },
                        new
                        {
                            Id = 2,
                            Body = "Post body 2",
                            CreatedOn = new DateTime(2020, 5, 28, 21, 59, 10, 482, DateTimeKind.Local).AddTicks(7416),
                            Title = "Post Title 2"
                        },
                        new
                        {
                            Id = 3,
                            Body = "Post body 3",
                            CreatedOn = new DateTime(2020, 5, 28, 21, 59, 10, 482, DateTimeKind.Local).AddTicks(7435),
                            Title = "Post Title 3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
